### ISSUE TITLE
Using the backend with google

### ISSUE THREAD

**Issue by thirty3** [Stackdriver/stackdriver-statsd-backend#13]
I have been trying to configure this backend for my GCE project, but it seems to either be abandoned or the documentation needs to be updated. I cannot find where to create the API-KEY.

The only API KEY I can find is called a legacy key and I get a 401 error when trying to use it with statsd

**Comment by katzj** [comment]
This backend only works for the old Stackdriver product, not Google Stackdriver.

Google Stackdriver has a new metrics API and so a new backend is needed to talk to it.

**Comment by thirty3** [comment]
That explains it, thank you :+1:
