### ISSUE TITLE
Google stackdriver support

### ISSUE THREAD

**Issue by AndrewDryga** [Stackdriver/stackdriver-statsd-backend#14]

**Comment by jacmrob** [comment]
Is this still being worked on?

**Comment by davidbernick** [comment]
+1

**Comment by igorpeshansky** [comment]
stackdriver-statsd-backend is not intended to work with Google Stackdriver. An alternate mechanism is under development. Please stay tuned.

**Comment by pataquets** [comment]
@igorpeshansky : Any news? ETA?
Thanks.

**Comment by igorpeshansky** [comment]
Sorry, no ETA yet. Still on the roadmap.
